version: '3'

services:
  jupyterlab:
    env_file:
      - .env
    build: .
    user: root
    environment:
      NB_UID: 1000
      NB_GID: 100
      GRANT_SUDO: "yes"
    volumes:
       - "./jupyter/work:/home/jovyan/work"
       - "./jupyter/Project.toml:/home/jovyan/Project.toml"
    privileged: true
    ports:
      - "8888:8888"
    restart: unless-stopped
    command: start.sh jupyter lab --NotebookApp.token=''
  postgres:
    container_name: postgres_container
    env_file:
      - .env
    image: mdillon/postgis
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data
    ports:
      - 5432:5432